name: Download proxies
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Clone proxypool
        uses: actions/checkout@v2
        with:
          repository: snakem982/proxypool
          ref: main
      - name: Find v2ray proxies
        run: |
          echo "Downloading v2ray proxies..."
          for file in `find . -name "v2ray*.txt"`; do
            echo "Downloading $file..."
            curl -o "$file" https://raw.githubusercontent.com/snakem982/proxypool/main/$file
            mv "$file" fww.txt
          done
      - name: Save proxies to my repository
        run: |
          echo "Saving proxies to my repository..."
          git config --global user.email "fangvv@gmail.com"
          git config --global user.name "fangvv"
          git add *.txt
          git commit -m "Add v2ray proxies"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push
