name: Backup Website

on:
  schedule:
    - cron: "0 9 * * *" # runs at 17:00 Beijing time

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Backup website
      run: |
        curl -o 8530.html http://faculty.bjtu.edu.cn/8530/ 
      # replace example.com with the URL you want to backup

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: website-backup
        path: 8530.html
