name: Search Source

on:
  push:
    branches:
      - master

jobs:

  search:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install requests
    - name: Search source code
      run: |
        python .github/workflows/wanshanziwo.py
        cat 1.txt >> $GITHUB_STEP_SUMMARY
    - name: Output result
      run: |
        echo "Result:"
