name: Search Source

on:
  push:
    branches:
      - master

jobs:

  search:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install requests
    - name: Search source code
      run: |
        python .github/workflows/search.py
        # 这里是上面给出的Python代码
    - name: Output result
      run: |
        echo "Result:"
        cat result.txt >> $GITHUB_STEP_SUMMARY
